apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-iap-app
  namespace: cloud-iap
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloud-iap-app
  template:
    metadata:
      labels:
        app: cloud-iap-app
    spec:
      containers:
        - name: app
          image: nginx:1.25.4
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
