apiVersion: v1
kind: Service
metadata:
  name: cloud-iap-app
  namespace: cloud-iap
spec:
  selector:
    app: cloud-iap-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
